/*----------------------------------------------------------------------
Compiler Generator Coco/R,
Copyright (c) 1990, 2004 Hanspeter Moessenboeck, University of Linz
extended by M. Loeberbauer & A. Woess, Univ. of Linz
ported to C++ by Csaba Balazs, University of Szeged
with improvements by Pat Terry, Rhodes University

This program is free software; you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by the 
Free Software Foundation; either version 2, or (at your option) any 
later version.

This program is distributed in the hope that it will be useful, but 
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
for more details.

You should have received a copy of the GNU General Public License along 
with this program; if not, write to the Free Software Foundation, Inc., 
59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

As an exception, it is allowed to write an extension of Coco/R that is
used as a plugin in non-free software.

If not otherwise stated, any source code generated by Coco/R (other than 
Coco/R itself) does not fall under the GNU General Public License.
-----------------------------------------------------------------------*/

#include "CharSet.h"
#include "Scanner.h"

namespace Coco
{

CharSet::CharSet()
    : head()
{
}

CharSet::CharSet(CharSet const & other)
    : head()
{
	for (auto & range : other)
    {
		Range r(range.from, range.to);
        head.push_back(r);
	}
}

CharSet::CharSet(CharSet && other)
    : head()
{
    this->head = std::move(other.head);
    other.head = {};
}

CharSet::~CharSet()
{
	Clear();
}
	
CharSet & CharSet::operator = (CharSet const & other)
{
    if (this != &other)
    {
        Clear();
	    for (auto & range : other.head)
        {
		    Range r(range.from, range.to);
            head.push_back(r);
	    }
    }
    return *this;
}

CharSet & CharSet::operator = (CharSet && other)
{
    this->head = std::move(other.head);
    other.head = {};
    return *this;
}

bool CharSet::Get(wchar_t i) const
{
	for (auto & range : head)
		if (i < range.from) 
            return false;
		else if (i <= range.to) 
            return true; // p.from <= i <= p.to
	return false;
}

void CharSet::Set(wchar_t i)
{
	Iterator cur = head.begin();
	while (cur != head.end() && i >= cur->from-1)
    {
		if (i <= cur->to + 1)
        { // (cur.from-1) <= i <= (cur.to+1)
			if (i == cur->from - 1) cur->from--;
			else if (i == cur->to + 1)
            {
				cur->to++;
				Iterator next = cur + 1;
				if (next != head.end() && cur->to == next->from - 1)
                {
					cur->to = next->to;
					cur->next = next->next;
					head.erase(next);
				};
			}
			return;
		}
		++cur;
	}
	Range n(i, i);
    head.insert(cur, n);
}

CharSet CharSet::Clone() const
{
	return CharSet(*this);
}

bool CharSet::Equals(CharSet const & s) const
{
	ConstIterator p = head.begin(), q = s.head.begin();
	while (p != head.end() && q != s.head.end())
    {
		if (p->from != q->from || p->to != q->to) 
            return false;
		++p; 
        ++q;
	}
	return (p == head.end()) && (q == s.head.end());
}

size_t CharSet::Count() const
{
	size_t n = 0;
	for (auto & range : head) 
        n += range.to - range.from + 1;
	return n;
}

wchar_t CharSet::First() const
{
	if (head.begin() != head.end()) 
        return head.begin()->from;
	return -1;
}

void CharSet::Or(CharSet const & s)
{
	for (auto & range : s.head)
		for (int i = range.from; i <= range.to; i++) 
            Set(i);
}

void CharSet::And(CharSet const & s)
{
	CharSet newSet;
    for (auto & range : head)
    {
		for (int i = range.from; i <= range.to; i++)
			if (s.Get(i)) 
                newSet.Set(i);
    }
	head = std::move(newSet.head);
    newSet.head = {};
}

void CharSet::Subtract(CharSet const & s)
{
	CharSet newSet;
	for (auto & range : head)
    {
		for (int i = range.from; i <= range.to; i++)
			if (!s.Get(i)) 
                newSet.Set(i);
	}
	head = std::move(newSet.head);
    newSet.head = {};
}

bool CharSet::Includes(CharSet const & s) const
{
	for (auto & range : s.head)
		for (int i = range.from; i <= range.to; i++)
			if (!Get(i)) 
                return false;
	return true;
}

bool CharSet::Overlaps(CharSet const & s) const
{
	for (auto & range : s.head)
		for (int i = range.from; i <= range.to; i++)
			if (Get(i)) 
                return true;
	return false;
}

void CharSet::Clear()
{
    head.clear();
}

void CharSet::Fill()
{
	Clear();
	head.push_back(Range(0, COCO_WCHAR_MAX));
}

} // namespace Coco
