/*-------------------------------------------------------------------------
DFA -- Generation of the Scanner Automaton
Compiler Generator Coco/R,
Copyright (c) 1990, 2004 Hanspeter Moessenboeck, University of Linz
extended by M. Loeberbauer & A. Woess, Univ. of Linz
ported to C++ by Csaba Balazs, University of Szeged
with improvements by Pat Terry, Rhodes University

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 2, or (at your option) any
later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

As an exception, it is allowed to write an extension of Coco/R that is
used as a plugin in non-free software.

If not otherwise stated, any source code generated by Coco/R (other than
Coco/R itself) does not fall under the GNU General Public License.
-------------------------------------------------------------------------*/

#include "ArrayList.h"
#include <sstream>
#include <stdlib.h>
#include <wchar.h>
#include "DFA.h"
#include "Tab.h"
#include "Parser.h"
#include "BitSet.h"
#include "Scanner.h"
#include "Generator.h"

namespace Coco
{

//---------- Output primitives
std::wstring DFA::Ch(wchar_t ch)
{
    std::wostringstream stream;
	if (ch < L' ' || ch >= 127 || ch == L'\'' || ch == L'\\')
		stream << (int)ch;
	else
		stream << L"L'" << ch << L"'";
	return stream.str();
}

std::wstring DFA::ChCond(wchar_t ch)
{
    std::wostringstream stream;
    stream << L"ch == " << Ch(ch);
	return std::wstring(stream.str());
}

void DFA::PutRange(CharSet const & s)
{
	for (CharSet::ConstIterator r = s.begin(); r != s.end(); ++r)
    {
		if (r->from == r->to)
        {
			std::wstring from = Ch(r->from);
			fwprintf(gen, L"ch == %ls", from.c_str());
		}
        else if (r->from == 0) 
        {
			std::wstring to = Ch(r->to);
			fwprintf(gen, L"ch <= %ls", to.c_str());
		}
        else
        {
			std::wstring from = Ch(r->from);
			std::wstring to = Ch(r->to);
			fwprintf(gen, L"(ch >= %ls && ch <= %ls)", from.c_str(), to.c_str());
		}
		if (r != s.end() - 1) 
            fwprintf(gen, L" || ");
	}
}

//---------- State handling

State * DFA::NewState()
{
	State *s = new State(); s->nr = ++lastStateNr;
	if (firstState == nullptr) 
        firstState = s; 
    else 
        lastState->next = s;
	lastState = s;
	return s;
}

void DFA::NewTransition(State * from, State * to, int typ, int sym, int tc)
{
	Target *t = new Target(to);
	Action *a = new Action(typ, sym, tc);
    a->target = t;
	from->AddAction(a);
	if (typ == Node::clas) 
        curSy->SetTokenKind(Symbol::TokenKind::ClassToken);
}

void DFA::CombineShifts()
{
	State *state;
	Action *a, *b, *c;
	for (state = firstState; state != nullptr; state = state->next)
    {
		for (a = state->firstAction; a != nullptr; a = a->next)
        {
			b = a->next;
			while (b != nullptr)
				if (a->target->state == b->target->state && a->tc == b->tc)
                {
					CharSet & seta = a->Symbols(tab); 
                    CharSet & setb = b->Symbols(tab);
					seta |= setb;
					a->ShiftWith(&seta, tab);
					c = b; b = b->next; state->DetachAction(c);
				} 
                else 
                    b = b->next;
		}
	}
}

void DFA::FindUsedStates(State *state, BitSet & used)
{
	if (used[state->nr]) 
        return;
	used.Set(state->nr, true);
	for (Action *a = state->firstAction; a != nullptr; a = a->next)
		FindUsedStates(a->target->state, used);
}

void DFA::DeleteRedundantStates()
{
	//State *newState = new State[State::lastNr + 1];
	State **newState = (State**) malloc (sizeof(State*) * (lastStateNr + 1));
	BitSet used(lastStateNr + 1);
	FindUsedStates(firstState, used);
	// combine equal final states
	for (State *s1 = firstState->next; s1 != nullptr; s1 = s1->next) // firstState cannot be final
		if (used[s1->nr] && s1->endOf != nullptr && s1->firstAction == nullptr && !(s1->ctx))
			for (State *s2 = s1->next; s2 != nullptr; s2 = s2->next)
				if (used[s2->nr] && s1->endOf == s2->endOf && s2->firstAction == nullptr && !(s2->ctx))
                {
					used.Set(s2->nr, false); 
                    newState[s2->nr] = s1;
				}

	State *state;
	for (state = firstState; state != nullptr; state = state->next)
		if (used[state->nr])
			for (Action *a = state->firstAction; a != nullptr; a = a->next)
				if (!(used[a->target->state->nr]))
					a->target->state = newState[a->target->state->nr];
	// delete unused states
	lastState = firstState; lastStateNr = 0; // firstState has number 0
	for (state = firstState->next; state != nullptr; state = state->next)
		if (used[state->nr])
        {
            state->nr = ++lastStateNr; 
            lastState = state;
        }
		else 
            lastState->next = state->next;
	free (newState);
}

State* DFA::TheState(Node * p)
{
	State *state;
	if (p == nullptr)
    {
        state = NewState(); 
        state->endOf = curSy; 
        return state;
    }
	else return p->state;
}

void DFA::Step(State *from, Node *p, BitSet & stepped)
{
	if (p == nullptr)
        return;
	stepped.Set(p->n, true);

	if (p->typ == Node::clas || p->typ == Node::chr)
    {
		NewTransition(from, TheState(p->next), p->typ, p->val, p->code);
	} 
    else if (p->typ == Node::alt)
    {
		Step(from, p->sub, stepped); 
        Step(from, p->down, stepped);
	}
    else if (p->typ == Node::iter)
    {
		if (tab->DelSubGraph(p->sub))
        {
			parser->SemanticError(L"contents of {...} must not be deletable");
			return;
		}
		if (p->next != nullptr && !(stepped[p->next->n])) 
            Step(from, p->next, stepped);
		Step(from, p->sub, stepped);
		if (p->state != from)
        {
			BitSet newStepped(tab->nodes.size());
			Step(p->state, p, newStepped);
		}
	} 
    else if (p->typ == Node::opt)
    {
		if (p->next != nullptr && !(stepped[p->next->n])) 
            Step(from, p->next, stepped);
		Step(from, p->sub, stepped);
	}
}

// Assigns a state n.state to every node n. There will be a transition from
// n.state to n.next.state triggered by n.val. All nodes in an alternative
// chain are represented by the same state.
// Numbering scheme:
//  - any node after a chr, clas, opt, or alt, must get a new number
//  - if a nested structure starts with an iteration the iter node must get a new number
//  - if an iteration follows an iteration, it must get a new number
void DFA::NumberNodes(Node * p, State * state, bool renumIter)
{
	if (p == nullptr) 
        return;
	if (p->state != nullptr) 
        return; // already visited;
	if ((state == nullptr) || ((p->typ == Node::iter) && renumIter)) 
        state = NewState();
	p->state = state;
	if (tab->DelGraph(p)) 
        state->endOf = curSy;

	if (p->typ == Node::clas || p->typ == Node::chr)
    {
		NumberNodes(p->next, nullptr, false);
	} 
    else if (p->typ == Node::opt)
    {
		NumberNodes(p->next, nullptr, false);
		NumberNodes(p->sub, state, true);
	} 
    else if (p->typ == Node::iter)
    {
		NumberNodes(p->next, state, true);
		NumberNodes(p->sub, state, true);
	} 
    else if (p->typ == Node::alt)
    {
		NumberNodes(p->next, nullptr, false);
		NumberNodes(p->sub, state, true);
		NumberNodes(p->down, state, renumIter);
	}
}

void DFA::FindTrans(Node *p, bool start, BitSet & marked)
{
	if (p == nullptr || marked[p->n]) 
        return;
	marked.Set(p->n, true);
	if (start)
    {
		BitSet stepped(tab->nodes.size());
		Step(p->state, p, stepped); // start of group of equally numbered nodes
	}

	if (p->typ == Node::clas || p->typ == Node::chr)
    {
		FindTrans(p->next, true, marked);
	} 
    else if (p->typ == Node::opt) 
    {
		FindTrans(p->next, true, marked); 
        FindTrans(p->sub, false, marked);
	} 
    else if (p->typ == Node::iter)
    {
		FindTrans(p->next, false, marked); 
        FindTrans(p->sub, false, marked);
	} 
    else if (p->typ == Node::alt)
    {
		FindTrans(p->sub, false, marked); 
        FindTrans(p->down, false, marked);
	}
}

void DFA::ConvertToStates(Node *p, Symbol *sym)
{
	curGraph = p; curSy = sym;
    if (tab->DelGraph(curGraph)) 
    {
        parser->SemanticError(L"token might be empty");
        return;
    }
	NumberNodes(curGraph, firstState, true);
	FindTrans(curGraph, true, BitSet(tab->nodes.size()));
	if (p->typ == Node::iter)
    {
		BitSet stepped(tab->nodes.size());
		Step(firstState, p, stepped);
	}
}

// match string against current automaton; store it either as a fixedToken or as a litToken
void DFA::MatchLiteral(std::wstring const & s, Symbol * sym)
{
	std::wstring subS = String::Create(s, 1, s.length()-2);
	std::wstring sUnescaped = tab->Unescape(subS);
	size_t i, len = sUnescaped.length();
	State *state = firstState;
	Action *a = nullptr;
	for (i = 0; i < len; i++)
    { // try to match s against existing DFA
		a = FindAction(state, sUnescaped[i]);
		if (a == nullptr) 
            break;
		state = a->target->state;
	}
	// if s was not totally consumed or leads to a non-final state => make new DFA from it
	if (i != len || state->endOf == nullptr)
    {
		state = firstState; i = 0; a = nullptr;
		dirtyDFA = true;
	}
	for (; i < len; i++)
    { // make new DFA for s[i..len-1]
		State *to = NewState();
		NewTransition(state, to, Node::chr, sUnescaped[i], Node::normalTrans);
		state = to;
	}
	Symbol *matchedSym = state->endOf;
	if (state->endOf == nullptr)
    {
		state->endOf = sym;
	} 
    else if (matchedSym->GetTokenKind() == Symbol::TokenKind::FixedToken || (a != nullptr && a->tc == Node::contextTrans))
    {
		// s matched a token with a fixed definition or a token with an appendix that will be cut off
        std::wostringstream stream;
		stream << L"tokens " << sym->GetName() << " and " << matchedSym->GetName() << " cannot be distinguished";
		parser->SemanticError(stream.str());
	} 
    else 
    { // matchedSym == classToken || classLitToken
		matchedSym->SetTokenKind(Symbol::TokenKind::ClassLitToken);
		sym->SetTokenKind(Symbol::TokenKind::LitToken);
	}
}

void DFA::SplitActions(State * state, Action * a, Action * b)
{
	Action *c; 
    CharSet & seta = a->Symbols(tab); 
    CharSet & setb = b->Symbols(tab);
	if (seta == setb)
    {
		a->AddTargets(b);
		state->DetachAction(b);
	} 
    else if (seta.Includes(setb)) 
    {
		CharSet & setc = seta.Clone(); 
        setc -= setb;
		b->AddTargets(a);
		a->ShiftWith(&setc, tab);
	} 
    else if (setb.Includes(seta))
    {
		CharSet setc = setb.Clone(); 
        setc -= seta;
		a->AddTargets(b);
		b->ShiftWith(&setc, tab);
	} 
    else 
    {
		CharSet setc(seta); 
        setc &= setb;
		seta -= setc;
		setb -= setc;
		a->ShiftWith(&seta, tab);
		b->ShiftWith(&setb, tab);
		c = new Action(0, 0, Node::normalTrans);  // typ and sym are set in ShiftWith
		c->AddTargets(a);
		c->AddTargets(b);
		c->ShiftWith(&setc, tab);
		state->AddAction(c);
	}
}

bool DFA::Overlap(Action * a, Action * b)
{
	if (a->typ == Node::chr)
		if (b->typ == Node::chr) 
            return (a->sym == b->sym);
		else
        {
            CharSet const & setb = tab->CharClassSet(b->sym);
            return setb.Get(a->sym);
        }
	else
    {
        CharSet const & seta = tab->CharClassSet(a->sym);
		if (b->typ == Node::chr) 
            return seta.Get(b->sym);
		else 
        {
            CharSet const & setb = tab->CharClassSet(b->sym); 
            return seta.Overlaps(setb);
        }
	}
}

bool DFA::MakeUnique(State * state)
{ // return true if actions were split
	bool changed = false;
	for (Action *a = state->firstAction; a != nullptr; a = a->next)
		for (Action *b = a->next; b != nullptr; b = b->next)
			if (Overlap(a, b))
            {
				SplitActions(state, a, b);
				changed = true;
			}
	return changed;
}

void DFA::MeltStates(State *state)
{
	bool changed, ctx;
	BitSet targets;
	Symbol *endOf;
	for (Action *action = state->firstAction; action != nullptr; action = action->next)
    {
		if (action->target->next != nullptr)
        {
			GetTargetStates(action, targets, endOf, ctx);
			Melted *melt = StateWithSet(targets);
			if (melt == nullptr)
            {
				State *s = NewState(); s->endOf = endOf; s->ctx = ctx;
				for (Target *targ = action->target; targ != nullptr; targ = targ->next)
					s->MeltWith(targ->state);
				do
                {
                    changed = MakeUnique(s);
                } while (changed);
				melt = NewMelted(targets, s);
			}
			action->target->next = nullptr;
			action->target->state = melt->state;
		}
	}
}

void DFA::FindCtxStates()
{
	for (State *state = firstState; state != nullptr; state = state->next)
		for (Action *a = state->firstAction; a != nullptr; a = a->next)
			if (a->tc == Node::contextTrans) 
                a->target->state->ctx = true;
}

void DFA::MakeDeterministic()
{
	State *state;
	bool changed;
	lastSimState = lastState->nr;
	maxStates = 2 * lastSimState; // heuristic for set size in Melted.set
	FindCtxStates();
	for (state = firstState; state != nullptr; state = state->next)
		do
        {
            changed = MakeUnique(state);
        } 
        while (changed);
	for (state = firstState; state != nullptr; state = state->next)
		MeltStates(state);
	DeleteRedundantStates();
	CombineShifts();
}

void DFA::PrintStates()
{
	fwprintf(trace, L"\n");
	fwprintf(trace, L"---------- states ----------\n");
	for (State *state = firstState; state != nullptr; state = state->next)
    {
		bool first = true;
		if (state->endOf == nullptr) fwprintf(trace, L"               ");
		else
        {
			std::wstring paddedName = tab->Name(state->endOf->GetName());
			fwprintf(trace, L"E(%12s)", paddedName.c_str());
		}
		fwprintf(trace, L"%3zd:", state->nr);
		if (state->firstAction == nullptr) fwprintf(trace, L"\n");
		for (Action *action = state->firstAction; action != nullptr; action = action->next)
        {
			if (first)
            {
                fwprintf(trace, L" "); 
                first = false;
            }
            else
                fwprintf(trace, L"                    ");

			if (action->typ == Node::clas) 
                fwprintf(trace, L"%ls", tab->classes[action->sym]->GetName().c_str());
			else 
                fwprintf(trace, L"%3s", Ch((wchar_t)action->sym).c_str());
			for (Target *targ = action->target; targ != nullptr; targ = targ->next)
            {
				fwprintf(trace, L"%3zd", targ->state->nr);
			}
			if (action->tc == Node::contextTrans) 
                fwprintf(trace, L" context\n"); 
            else 
                fwprintf(trace, L"\n");
		}
	}
	fwprintf(trace, L"\n---------- character classes ----------\n");
	tab->WriteCharClasses();
}

//---------------------------- actions --------------------------------

Action* DFA::FindAction(State * state, wchar_t ch)
{
	for (Action * a = state->firstAction; a != nullptr; a = a->next)
		if (a->typ == Node::chr && ch == a->sym) 
            return a;
		else if (a->typ == Node::clas)
        {
			CharSet const & s = tab->CharClassSet(a->sym);
			if (s.Get(ch)) 
                return a;
		}
	return nullptr;
}

void DFA::GetTargetStates(Action * a, BitSet & targets, Symbol* & endOf, bool & ctx)
{
	// compute the set of target states
	targets = BitSet(maxStates); 
    endOf = nullptr;
	ctx = false;
	for (Target *t = a->target; t != nullptr; t = t->next)
    {
		size_t stateNr = t->state->nr;
		if (stateNr <= lastSimState)
        {
            targets.Set(stateNr, true);
        }
		else
        { 
            targets |= MeltedSet(stateNr);
        }
		if (t->state->endOf != nullptr)
        {
			if (endOf == nullptr || endOf == t->state->endOf) 
            {
				endOf = t->state->endOf;
			}
			else
            {
				wprintf(L"Tokens %ls and %ls cannot be distinguished\n", endOf->GetName().c_str(), t->state->endOf->GetName().c_str());
				errors->count++;
			}
		}
		if (t->state->ctx)
        {
			ctx = true;
			// The following check seems to be unnecessary. It reported an error
			// if a symbol + context was the prefix of another symbol, e.g.
			//   s1 = "a" "b" "c".
			//   s2 = "a" CONTEXT("b").
			// But this is ok.
			// if (t.state.endOf != null) {
			//   Console.WriteLine("Ambiguous context clause");
			//	 Errors.count++;
			// }
		}
	}
}


//------------------------- melted states ------------------------------


Melted* DFA::NewMelted(BitSet const & set, State * state)
{
	Melted * m = new Melted(set, state);
	m->next = firstMelted; 
    firstMelted = m;
	return m;

}

BitSet const & DFA::MeltedSet(size_t nr)
{
	Melted * m = firstMelted;
	while (m != nullptr)
    {
		if (m->state->nr == nr) 
            return m->set; 
        else 
            m = m->next;
	}
    throw std::invalid_argument("Invalid set number");
}

Melted * DFA::StateWithSet(BitSet const & s)
{
	for (Melted * m = firstMelted; m != nullptr; m = m->next)
		if (s == m->set)
            return m;
	return nullptr;
}


//------------------------ comments --------------------------------

std::wstring DFA::CommentStr(Node * p)
{
	StringBuilder s = StringBuilder();
	while (p != nullptr)
    {
		if (p->typ == Node::chr)
        {
			s.Append((wchar_t)p->val);
		}
        else if (p->typ == Node::clas)
        {
			CharSet const & set = tab->CharClassSet(p->val);
			if (set.Count() != 1) 
                parser->SemanticError(L"character set contains more than 1 character");
			s.Append(set.First());
		}
		else 
            parser->SemanticError(L"comment delimiters may not be structured");
		p = p->next;
	}
	if (s.GetLength() == 0 || s.GetLength() > 2)
    {
		parser->SemanticError(L"comment delimiters must be 1 or 2 characters long");
		s = StringBuilder(L"?");
	}
	return s.ToString();
}


void DFA::NewComment(Node * from, Node * to, bool nested)
{
	Comment *c = new Comment(CommentStr(from), CommentStr(to), nested);
	c->next = firstComment; firstComment = c;
}


//------------------------ scanner generation ----------------------

void DFA::GenComBody(Comment * com)
{
	fwprintf(gen, L"\t\tfor(;;) {\n");

	std::wstring res = ChCond(com->stop[0]);
	fwprintf(gen, L"\t\t\tif (%ls) ", res.c_str());
	fwprintf(gen, L"{\n");

	if (com->stop.length() == 1)
    {
		fwprintf(gen, L"\t\t\t\tlevel--;\n");
		fwprintf(gen, L"\t\t\t\tif (level == 0) { oldEols = line - line0; NextCh(); return true; }\n");
		fwprintf(gen, L"\t\t\t\tNextCh();\n");
	} 
    else
    {
		fwprintf(gen, L"\t\t\t\tNextCh();\n");
		std::wstring res = ChCond(com->stop[1]);
		fwprintf(gen, L"\t\t\t\tif (%ls) {\n", res.c_str());
		fwprintf(gen, L"\t\t\t\t\tlevel--;\n");
		fwprintf(gen, L"\t\t\t\t\tif (level == 0) { oldEols = line - line0; NextCh(); return true; }\n");
		fwprintf(gen, L"\t\t\t\t\tNextCh();\n");
		fwprintf(gen, L"\t\t\t\t}\n");
	}
	if (com->nested)
    {
		fwprintf(gen, L"\t\t\t}");
		std::wstring res = ChCond(com->start[0]);
		fwprintf(gen, L" else if (%ls) ", res.c_str());
		fwprintf(gen, L"{\n");
		if (com->stop.length() == 1)
			fwprintf(gen, L"\t\t\t\tlevel++; NextCh();\n");
		else
        {
			fwprintf(gen, L"\t\t\t\tNextCh();\n");
			std::wstring res = ChCond(com->start[1]);
			fwprintf(gen, L"\t\t\t\tif (%ls) ", res.c_str());
			fwprintf(gen, L"{\n");
			fwprintf(gen, L"\t\t\t\t\tlevel++; NextCh();\n");
			fwprintf(gen, L"\t\t\t\t}\n");
		}
	}
	fwprintf(gen, L"\t\t\t} else if (ch == buffer->EoF) return false;\n");
	fwprintf(gen, L"\t\t\telse NextCh();\n");
	fwprintf(gen, L"\t\t}\n");
}

void DFA::GenCommentHeader(Comment * com, int i)
{
	fwprintf(gen, L"\tbool Comment%d();\n", i);
}

void DFA::GenComment(Comment * com, int i)
{
	fwprintf(gen, L"\n");
	fwprintf(gen, L"bool Scanner::Comment%d() ", i);
	fwprintf(gen, L"{\n");
	fwprintf(gen, L"\tint level = 1, pos0 = pos, line0 = line, col0 = col, charPos0 = charPos;\n");
	if (com->start.length() == 1)
    {
		fwprintf(gen, L"\tNextCh();\n");
		GenComBody(com);
	}
    else
    {
		fwprintf(gen, L"\tNextCh();\n");
		std::wstring res = ChCond(com->start[1]);
		fwprintf(gen, L"\tif (%ls) ", res.c_str());
		fwprintf(gen, L"{\n");

		fwprintf(gen, L"\t\tNextCh();\n");
		GenComBody(com);

		fwprintf(gen, L"\t} else {\n");
		fwprintf(gen, L"\t\tbuffer->SetPos(pos0); NextCh(); line = line0; col = col0; charPos = charPos0;\n");
		fwprintf(gen, L"\t}\n");
		fwprintf(gen, L"\treturn false;\n");
	}
	fwprintf(gen, L"}\n");
}

std::wstring DFA::SymName(Symbol * sym)
{ // real name value is stored in Tab.literals
	if (('a'<=sym->GetName()[0] && sym->GetName()[0]<='z') ||
		('A'<=sym->GetName()[0] && sym->GetName()[0]<='Z'))
    { //Char::IsLetter(sym->name[0])

		Iterator *iter = tab->literals->GetIterator();
		while (iter->HasNext())
        {
			DictionaryEntry *e = iter->Next();
			if (e->val == sym)
                return e->key;
		}
	}
	return sym->GetName();
}

void DFA::GenLiterals()
{
	Symbol *sym;

	std::vector<Symbol *> *ts[2];
	ts[0] = &tab->terminals;
	ts[1] = &tab->pragmas;

	for (int i = 0; i < 2; ++i)
    {
		for (int j = 0; j < ts[i]->size(); j++)
        {
			sym = (*ts)[i][j];
			if (sym->GetTokenKind() == Symbol::TokenKind::LitToken)
            {
				std::wstring name = SymName(sym);
				if (ignoreCase)
                {
					name = String::CreateLower(name);
				}
				// sym.name stores literals with quotes, e.g. "\"Literal\""

				fwprintf(gen, L"\tkeywords.set(L");
				// write keyword, escape non printable characters
				for (int k = 0; name[k] != L'\0'; k++)
                {
					wchar_t c = name[k];
					fwprintf(gen, (c >= 32 && c <= 127) ? L"%lc" : L"\\x%04x", c);
				}
				fwprintf(gen, L", %zd);\n", sym->GetSymbolNumber());
			}
		}
	}
}

size_t DFA::GenNamespaceOpen(std::string const & nsName)
{
	if (nsName.empty())
    {
		return 0;
	}
	const size_t len = nsName.length();
	size_t startPos = 0;
	size_t nrOfNs = 0;
	do
    {
		size_t curLen = String::IndexOf(nsName, startPos, COCO_CPP_NAMESPACE_SEPARATOR);
		if (curLen == std::string::npos)
        { 
            curLen = len - startPos;
        }
		std::string curNs = String::Create(nsName, startPos, curLen);
		fwprintf(gen, L"namespace %hs {\n", curNs.c_str());
		startPos = startPos + curLen + 1;
		if (startPos < len && nsName[startPos] == COCO_CPP_NAMESPACE_SEPARATOR)
        {
			++startPos;
		}
		++nrOfNs;
	} while (startPos < len);
	return nrOfNs;
}

void DFA::GenNamespaceClose(size_t nrOfNs)
{
	for (size_t i = 0; i < nrOfNs; ++i)
    {
		fwprintf(gen, L"} // namespace\n");
	}
}

void DFA::CheckLabels()
{
	int i;
	State *state;
	Action *action;

	for (i = 0; i < lastStateNr+1; i++)
    {
		existLabel[i] = false;
	}

	for (state = firstState->next; state != nullptr; state = state->next)
    {
		for (action = state->firstAction; action != nullptr; action = action->next)
        {
			existLabel[action->target->state->nr] = true;
		}
	}
}

void DFA::WriteState(State * state)
{
	Symbol *endOf = state->endOf;
	fwprintf(gen, L"\t\tcase %zd:\n", state->nr);
	if (existLabel[state->nr])
		fwprintf(gen, L"\t\t\tcase_%zd:\n", state->nr);

	if (endOf != nullptr && state->firstAction != nullptr)
    {
		fwprintf(gen, L"\t\t\trecEnd = pos; recKind = %zd;\n", endOf->GetSymbolNumber());
	}
	bool ctxEnd = state->ctx;

	for (Action *action = state->firstAction; action != nullptr; action = action->next)
    {
		if (action == state->firstAction) 
            fwprintf(gen, L"\t\t\tif (");
		else 
            fwprintf(gen, L"\t\t\telse if (");
		if (action->typ == Node::chr)
        {
			std::wstring res = ChCond((wchar_t)action->sym);
			fwprintf(gen, L"%ls", res.c_str());
		} 
        else 
            PutRange(tab->CharClassSet(action->sym));
		fwprintf(gen, L") {");

		if (action->tc == Node::contextTrans)
        {
			fwprintf(gen, L"apx++; "); ctxEnd = false;
		} 
        else if (state->ctx)
			fwprintf(gen, L"apx = 0; ");
		fwprintf(gen, L"AddCh(); goto case_%zd;", action->target->state->nr);
		fwprintf(gen, L"}\n");
	}
	if (state->firstAction == nullptr)
		fwprintf(gen, L"\t\t\t{");
	else
		fwprintf(gen, L"\t\t\telse {");
	if (ctxEnd)
    { // final context state: cut appendix
		fwprintf(gen, L"\n");
		fwprintf(gen, L"\t\t\t\ttlen -= apx;\n");
		fwprintf(gen, L"\t\t\t\tSetScannerBehindT();");

		fwprintf(gen, L"\t\t\t\tbuffer->SetPos(t->pos); NextCh(); line = t->line; col = t->col;\n");
		fwprintf(gen, L"\t\t\t\tfor (int i = 0; i < tlen; i++) NextCh();\n");
		fwprintf(gen, L"\t\t\t\t");
	}
	if (endOf == nullptr)
    {
		fwprintf(gen, L"goto case_0;}\n");
	} 
    else
    {
		fwprintf(gen, L"t->kind = %zd; ", endOf->GetSymbolNumber());
		if (endOf->GetTokenKind() == Symbol::TokenKind::ClassLitToken)
        {
			if (ignoreCase)
            {
				fwprintf(gen, L"wchar_t *literal = coco_string_create_lower(tval, 0, tlen); t->kind = keywords.get(literal, t->kind); coco_string_delete(literal); break;}\n");
			}
            else 
            {
				fwprintf(gen, L"wchar_t *literal = coco_string_create(tval, 0, tlen); t->kind = keywords.get(literal, t->kind); coco_string_delete(literal); break;}\n");
			}
		} 
        else 
        {
			fwprintf(gen, L"break;}\n");
		}
	}
}

void DFA::WriteStartTab()
{
	bool firstRange = true;
	for (Action *action = firstState->firstAction; action != nullptr; action = action->next)
    {
		size_t targetState = action->target->state->nr;
		if (action->typ == Node::chr)
        {
			fwprintf(gen, L"\tstart.set(%d, %zd);\n", action->sym, targetState);
		} 
        else
        {
			CharSet const & s = tab->CharClassSet(action->sym);
        	for (CharSet::ConstIterator r = s.begin(); r != s.end(); ++r)
            {
				if (firstRange)
                {
					firstRange = false;
					fwprintf(gen, L"\tint i;\n");
				}
				fwprintf(gen, L"\tfor (i = %d; i <= %d; ++i) start.set(i, %zd);\n", r->from, r->to, targetState);
			}
		}
	}
	fwprintf(gen, L"\t\tstart.set(Buffer::EoF, -1);\n");
}

void DFA::WriteScanner()
{
	Generator g = Generator(tab, errors);
	fram = g.OpenFrame("Scanner.frame");
	gen = g.OpenGen("Scanner.h");
	if (dirtyDFA) 
        MakeDeterministic();

	// Header
	g.GenCopyright();
	g.SkipFramePart(L"-->begin");
	
	g.CopyFramePart(L"-->prefix");
	g.GenPrefixFromNamespace();

	g.CopyFramePart(L"-->prefix");
	g.GenPrefixFromNamespace();

	g.CopyFramePart(L"-->namespace_open");
	size_t nrOfNs = GenNamespaceOpen(tab->nsName);

	g.CopyFramePart(L"-->casing0");
	if (ignoreCase)
    {
		fwprintf(gen, L"\twchar_t valCh;       // current input character (for token.val)\n");
	}
	g.CopyFramePart(L"-->commentsheader");
	Comment * com = firstComment;
	int cmdIdx = 0;
	while (com != nullptr)
    {
		GenCommentHeader(com, cmdIdx);
		com = com->next; cmdIdx++;
	}

	g.CopyFramePart(L"-->namespace_close");
	GenNamespaceClose(nrOfNs);

	g.CopyFramePart(L"-->implementation");
	fclose(gen);

	// Source
	gen = g.OpenGen("Scanner.cpp");
	g.GenCopyright();
	g.SkipFramePart(L"-->begin");
	g.CopyFramePart(L"-->namespace_open");
	nrOfNs = GenNamespaceOpen(tab->nsName);

	g.CopyFramePart(L"-->declarations");
	fwprintf(gen, L"\tmaxT = %zd;\n", tab->terminals.size() - 1);
	fwprintf(gen, L"\tnoSym = %zd;\n", tab->noSym->GetSymbolNumber());
	WriteStartTab();
	GenLiterals();

	g.CopyFramePart(L"-->initialization");
	g.CopyFramePart(L"-->casing1");
	if (ignoreCase)
    {
		fwprintf(gen, L"\t\tvalCh = ch;\n");
		fwprintf(gen, L"\t\tif ('A' <= ch && ch <= 'Z') ch = ch - 'A' + 'a'; // ch.ToLower()");
	}
	g.CopyFramePart(L"-->casing2");
	fwprintf(gen, L"\t\ttval[tlen++] = ");
	if (ignoreCase)
        fwprintf(gen, L"valCh;"); 
    else
        fwprintf(gen, L"ch;");

	g.CopyFramePart(L"-->comments");
	com = firstComment; cmdIdx = 0;
	while (com != nullptr)
    {
		GenComment(com, cmdIdx);
		com = com->next; cmdIdx++;
	}

	g.CopyFramePart(L"-->scan1");
	fwprintf(gen, L"\t\t\t");
	if (tab->ignored.Count() > 0)
        PutRange(tab->ignored);
    else
        fwprintf(gen, L"false");

	g.CopyFramePart(L"-->scan2");
	if (firstComment != nullptr)
    {
		fwprintf(gen, L"\tif (");
		com = firstComment; cmdIdx = 0;
		while (com != nullptr)
        {
			std::wstring res = ChCond(com->start[0]);
			fwprintf(gen, L"(%ls && Comment%d())", res.c_str(), cmdIdx);
			if (com->next != nullptr)
            {
				fwprintf(gen, L" || ");
			}
			com = com->next; cmdIdx++;
		}
		fwprintf(gen, L") return NextToken();");
	}
	if (hasCtxMoves)
    { 
        fwprintf(gen, L"\n"); 
        fwprintf(gen, L"\tint apx = 0;");
    } /* pdt */
	g.CopyFramePart(L"-->scan3");

	/* CSB 02-10-05 check the Labels */
	existLabel = new bool[lastStateNr+1];
	CheckLabels();
	for (State *state = firstState->next; state != nullptr; state = state->next)
		WriteState(state);
	delete [] existLabel;

	g.CopyFramePart(L"-->namespace_close");
	GenNamespaceClose(nrOfNs);

	g.CopyFramePart(L"");
	fclose(gen);
}

DFA::DFA(Parser * parser)
{
	this->parser = parser;
	tab = parser->tab;
	errors = parser->errors;
	trace = parser->trace;
	firstState = nullptr; lastState = nullptr; lastStateNr = -1;
	firstState = NewState();
	firstMelted = nullptr; firstComment = nullptr;
	ignoreCase = false;
	dirtyDFA = false;
	hasCtxMoves = false;
}

}; // namespace
