/*-------------------------------------------------------------------------
Compiler Generator Coco/R,
Copyright (c) 1990, 2004 Hanspeter Moessenboeck, University of Linz
extended by M. Loeberbauer & A. Woess, Univ. of Linz
ported to C++ by Csaba Balazs, University of Szeged
with improvements by Pat Terry, Rhodes University

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 2, or (at your option) any
later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

As an exception, it is allowed to write an extension of Coco/R that is
used as a plugin in non-free software.

If not otherwise stated, any source code generated by Coco/R (other than
Coco/R itself) does not fall under the GNU General Public License.
-------------------------------------------------------------------------*/

#include "Position.h"

namespace Coco
{

const Position Position::Null;

Position::Position()
    : beg()
    , end()
    , col()
    , line()
{
}

Position::Position(size_t beg, size_t end, size_t col, size_t line)
    : beg(beg)
    , end(end)
    , col(col)
    , line(line)
{
}

Position::Position(Position const & other)
    : beg(other.beg)
    , end(other.end)
    , col(other.col)
    , line(other.line)
{
}

Position & Position::operator =(Position const & other)
{
    if (this != &other)
    {
        this->beg = other.beg;
        this->end = other.end;
        this->col = other.col;
        this->line = other.line;
    }
    return *this;
}

Position::operator bool() const
{
    return !this ->operator !();
}

bool Position::operator !() const
{
    return (beg == 0) && (end == 0);
}

} // namespace Coco
